-- create table customer(
--     id number primary key ,
--     username nvarchar2(20),
--     password nvarchar2(15),
--     firstname nvarchar2(20),
--     lastname nvarchar2(20),
--     nationllid nvarchar2(10),
--     phone nvarchar2(10),
--     email nvarchar2(50),
--     address nvarchar2(100),
--     dateofbirth date,
--     registrationdate date
-- );

-- create sequence customer_seq start with 1 increment by 1;

-- CREATE table account(
--     accountid number primary key ,
--     balance number,
--     opendate date,
--     status nvarchar2(10),
--     customerid number,
--     foreign key (customerid) references customer(id)
-- );

-- create sequence account_seq start with 1 increment by 1;

-- create table transaction(
--     transactionid number primary key ,
--     transactiontype nvarchar2(10),
--     amount float,
--     transactiondate date,
--     accountid number,
--     foreign key (accountid) references account(accountid)
-- );

-- create sequence transaction_seq start with 1 increment by 1;

-- CREATE VIEW transaction_report AS
-- SELECT
--     -- تمام فیلدهای TRANSACTION
--     transaction_table.transactionid          AS transaction_id,
--     transaction_table.transactiontype        AS transaction_type,
--     transaction_table.amount                 AS amount,
--     transaction_table.transactiondate        AS transaction_date,
--     transaction_table.accountid              AS transaction_account_id,
--
--     -- تمام فیلدهای ACCOUNT (حساب)
--     account_table.ACCOUNTID              AS account_id,
--     account_table.balance                    AS account_balance,
--     account_table.opendate                   AS account_open_date,
--     account_table.status                     AS account_status,
--     account_table.customerid                 AS account_customer_id,
--
--     -- تمام فیلدهای CUSTOMER (مشتری)
--     customer_table.id                        AS customer_id,
--     customer_table.username                  AS customer_username,
--     customer_table.password                  AS customer_password,
--     customer_table.firstname                 AS customer_firstname,
--     customer_table.lastname                  AS customer_lastname,
--     customer_table.nationllid                AS customer_nationallid,
--     customer_table.phone                     AS customer_phone,
--     customer_table.email                     AS customer_email,
--     customer_table.address                   AS customer_address,
--     customer_table.dateofbirth               AS customer_dateofbirth,
--     customer_table.registrationdate          AS customer_registrationdate
--
-- FROM
--     TRANSACTION transaction_table
--
-- INNER JOIN
--     ACCOUNT  account_table
--     ON transaction_table.accountid = account_table.accountid
--
-- INNER JOIN
--     CUSTOMER  customer_table
--     ON account_table.customerid = customer_table.id;

-- CREATE TABLE APP_LOG (
--                          LOG_ID       NUMBER(20)     PRIMARY KEY,
--                          LOG_TIME     TIMESTAMP      NOT NULL,
--                          LOG_LEVEL    VARCHAR2(10)   NOT NULL,
--                          LOGGER_NAME  VARCHAR2(254)  NOT NULL,
--                          LOG_MESSAGE  VARCHAR2(4000) NOT NULL
-- );
--
-- CREATE SEQUENCE APP_LOG_SEQ
--     START WITH 1
--     INCREMENT BY 1;